<a href="https://colab.research.google.com/github/greatsangho/python_study/blob/main/20240828_day_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

pandas
 - csv 및 기타 파일을 객체형태로 관리 모듈(프레임 웍)

In [ ]:
# !pip install pandas
# !conda install pandas

In [ ]:
import pandas as pd

In [ ]:
pd.DataFrame() # 빈 데이터 프레임 클래스 초기화
d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(d)
df # 딕셔너리는 세로로

col1  col2
0     1     3
1     2     4

In [ ]:
import random
data = [random.sample(range(1,46),6) for i in range(20)]
df = pd.DataFrame(data)
df # 리스트는 가로로

0   1   2   3   4   5
0   35  34  33   7  11  39
1    1  35  15  43  13   9
2   41  19  37   2  34  20
3   10  29  11  25  30  21
4   24   9  35   6  10  15
5   36  29  23  16   7  11
6   17  34  35  40  42  12
7   41  36  40  12   4  19
8   40  16  10  38  32  23
9   27  32  39   1  28  24
10  23  17  11  25  10  20
11   3  43  25  39  44  36
12  42  40  41  25  44  10
13  35  45  19  14  32  30
14  19  33  30  42   8  11
15   5  28  11  16  41  22
16  34  31  15   2  21  11
17  43  44  12  34  27  38
18  32   5   6  39  28   9
19  32   6  37  23  16   2

In [ ]:
# 이름 붙이기
cols = ['name'+str(i) for i in range(20)]
df = pd.DataFrame(dict(zip(cols, data)), index=['서울','경기','강원','대구','울산','부산'])
df['name0'] # 시리즈, DataFrame --> 시리즈의 집합
df['name0'].values # 넘파이 배열
df['name0'].index # 인덱스
df['name0'].dtype # 데이터 타입
df['name0'].value_counts() # 빈도수
df['name0'].unique() # 고유값
df['name0'].nunique() # 고유값 개수

6

In [ ]:
# https://www.data.go.kr/
df = pd.read_csv('/content/drive/MyDrive/datafile/국가보훈부_보훈의료 위탁병원 현황_20231023.csv',encoding='ms949') # 주로 utf8로 표준화 안 해놓음
df.head(2)

기준일  연번       지역     위탁병원명  병상수  진료과수          전화번호            주소  \
0  2023-10-23   1  강원도 강릉시    강릉동인병원  383    21  033)651-6167  강릉대로419번길 42   
1  2023-10-23   2  강원도 강릉시  강릉연세요양병원   99     3  033)645-1400        옥가로 70   

   비고  
0  종합  
1  요양

In [ ]:
df['지역'].value_counts() # 기본이 내림차순으로 출력

지역
경남 창원시     11
제주도 제주시     8
충북 청주시      7
경기도 용인시     6
전남 완도군      6
           ..
경북 칠곡군      1
경북 청송군      1
경북 울릉군      1
경북 영양군      1
경기도 이천시     1
Name: count, Length: 227, dtype: int64

넘파이 기본개념
 - 수학적 계산을 위한 리스트인데.. 구분하기 위해서 넘파이 배열

In [ ]:
import numpy as np
np.array([1,2,3]) # 리스트 -> 넘파이 배열
# 두개의 리스트의 각각의 요소끼리 사칙연산을 해보세요
a = random.sample(range(1,10),5)
b = random.sample(range(1,10),5)
print(a,b)
print([x+y for x,y in zip(a,b)])
print([x-y for x,y in zip(a,b)])
print([x*y for x,y in zip(a,b)])
print([x/y for x,y in zip(a,b)])
a+b

[8, 6, 9, 4, 5] [7, 4, 9, 6, 8]
[15, 10, 18, 10, 13]
[1, 2, 0, -2, -3]
[56, 24, 81, 24, 40]
[1.1428571428571428, 1.5, 1.0, 0.6666666666666666, 0.625]


[8, 6, 9, 4, 5, 7, 4, 9, 6, 8]

In [ ]:
a_numpy = np.array(a)
b_numpy = np.array(b)
print(a_numpy+b_numpy)
print(a_numpy-b_numpy)
print(a_numpy*b_numpy)
a_numpy/b_numpy

[15 10 18 10 13]
[ 1  2  0 -2 -3]
[56 24 81 24 40]


array([1.14285714, 1.5       , 1.        , 0.66666667, 0.625     ])

In [ ]:
# 도서관리 프로그램
# 저자, 제목, 발행연도, isbn 이런 데이터의 자동 순번을 부여 --> 클래스 변수 응용(Serial number 채번)
# CRUD
# 클래스 형태로 - 다 완성이 되면 모듈로 저장 -> 데이터베이스와 연동(추후) -> Flask or Streamlit 화면구성

- 기능 명세서
- 프로그램 설계서

In [ ]:
# 기능 명세서
# 1. 메뉴 : 사용자에게 메뉴를 보여주고 선택하게 한다
# 2. 생성 : 책이 입고되면 데이터베이스에 책 정보를 입력한다
# 3. 삭제 : 조회 후 물리적으로 삭제하지 않고 flag를 두어 업데이트 한다.(y/n)
# 4. 조회 : 저자, 제목, 발행연도, isbn 각각 조회가 가능하도록 -> 결과는 리스트나 딕셔너리나... 자료구조형태 객체
# 5. 업데이트 : 조회 후 업데이트

In [ ]:
# 프로그램 설계서
# class Book
 # 책 데이터 및 delete_ny ='n'

# class BookStore
# 함수명, 클래스명 지정해주고 구체적인 동작 내용을 기술하고 기능명세서의 내용을 반영한다
# 메뉴
 # 함수명 displayMenu()
 # 기능명세서 번호 : 1
 # 내용 : 콘솔에 print함수를 이용해서 다음과 같은 기능을 구현한다
  # 1. 입력      2. 조회
  # 3. 업데이트  4. 삭제
  # 5. 종료

# 생성
 # 함수명 createBook()
 # 기능명세서 번호 : 2
 # 내용:
  # 저자, 제목, 발행년도, isbn = input().split()
  # book 객체를 리스트에 저장

# 삭제
 # 함수명 deleteBook()
 # 기능명세서 번호 : 3
  # 조회 후 delete_yn을 y로 업데이트

# 조회
 # 함수명 searchBook()
 # 기능명세서 번호 : 4
  # 조회조건을 설정하고 조회 데이터르 입력받아서 조회한다
  # 조회결과를 리스트에 담아 반환한다

# 업데이트
 # 함수명 updateBook()
 # 기능명세서 번호: 5
  # 조회한 데이터를 보여주고 업데이트할 데이터를 선택
  # 업데이트할 데이터를 입력받고
  # 업데이트 한다

In [ ]:
class Book: # DTO, VO 데이터 클래스
  serial_number = 0
  def __init__(self, author, title, year, isbn, amt=1):
    Book.serial_number += 1
    self.author = author
    self.title = title
    self.year = year
    self.isbn = isbn
    self.delete_yn = 'n'
    self.amt = amt
    self.id = Book.serial_number # PK(primary key)

  def __eq__(self,__o: object) -> bool: # 재정의
    return self.isbn == __o.isbn
  def __ne__(self,__o: object) -> bool: # 재정의
    return self.isbn != __o.isbn

  def __str__(self):
    return f'{self.id} {self.author} {self.title} {self.year} {self.isbn} {self.delete_yn} {self.amt}'

In [ ]:
# 화이트홀 2024-09-01 카를로_로벨리 9791165349936 100
author, title, year, isbn, amt = input("Input book data(author, title, year, isbn, amt) >").split()
book1 = Book(author, title, year, isbn, amt)
books1 = [book1]

author, title, year, isbn, amt = input("Input book data(author, title, year, isbn, amt) >").split()
book2 = Book(author, title, year, isbn, amt)
book2 in books1

Input book data(author, title, year, isbn, amt) >화이트홀 2024-09-01 카를로_로벨리 9791165349936 100
Input book data(author, title, year, isbn, amt) >화이트홀 2024-09-01 카를로_로벨리 9791165349934 100


False

In [ ]:
# books = [book,book,book,book,book]

In [ ]:
# 프로그램설계서의 메뉴
def display_get_Menu():
  print('메뉴 번호를 입력하세요')
  print('1. 입력\t\t2. 조회')
  print('3. 업데이트\t4. 삭제')
  print('5. 종료')
  menu = input('input > ')
  if menu == '1':
    return menu
  elif menu == '2':
    return menu
  elif menu == '3':
    return menu
  elif menu == '4':
    return menu
  elif menu == '5':
    print('프로그램을 종료합니다')
  else:
    raise Exception("잘못된 입력입니다")
print(display_get_Menu())

메뉴 번호를 입력하세요
1. 입력		2. 조회
3. 업데이트	4. 삭제
5. 종료
input > 1
1


In [ ]:
# 프로그램 설계서의 입력
def creat_book(bookstore):
  author, title, year, isbn, amt = input("Input book data(author, title, year, isbn, amt) >").strip().split()
  book1 = Book(author, title, year, isbn, amt)
  bookstore.books = book1

bookstore = BookStore()
creat_book(bookstore)
for book in bookstore.books:  # 데이터베이스의 모든 값을 출력
  print(book)

Input book data(author, title, year, isbn, amt) >저어자 파파이선  2023 1230001010 40
10 저어자 파파이선 2023 1230001010 n 40


In [ ]:
# 조회
# 조회 조건을 설정하고 검색어를 입력해서 book을 검색
# 데이터중에 delete_yn이 n인 항목만 조회
# 검색어 조회조건을 입력하면
def search_book(bookstore):
  search, condition = input("검색어 조회조건(검색어, 저자, 제목, 년도, isbn) >").strip().split()
  if condition == '저자':
    return [book for book in bookstore.books if book.author == search and book.delete_yn.lower() == 'n']
  elif condition == '제목':
    return [book for book in bookstore.books if book.title == search and book.delete_yn.lower() == 'n']
  elif condition == '년도':
    return [book for book in bookstore.books if book.year == search and book.delete_yn.lower() == 'n']
  elif condition == 'isbn':
    return [book for book in bookstore.books if book.isbn == search and book.delete_yn.lower() == 'n']
  else:
    raise Exception("잘못된 입력입니다")

In [ ]:
result = search_book(bookstore)
for data in result:
  print(data)

검색어 조회조건(검색어, 저자, 제목, 년도, isbn) >저어자 저자
10 저어자 파파이선 2023 1230001010 n 40


In [ ]:
# 삭제
# 조회를 한 후에 삭제하고 싶은 번호를 선택하면
# ex) 11 -> 11번에 대한 데이터의 delete_yn = 'y' 업데이트
# ex) 11,12 -> 11,12번에 대한 데이터의 delete_yn = 'y' 업데이트
result = search_book(bookstore)
for data in result:
  print(data)

delete_str = input('삭제할 번호(여러개일 경우,로 구분) > ').strip().split(',')
for id in delete_str: # 숫자로 바꿨으면 map(int, delete_str)
  for book in bookstore.books:
    if book.id == id:
      book.delete_yn = 'y'

검색어 조회조건(검색어, 저자, 제목, 년도, isbn) >저어자 저자
10 저어자 파파이선 2023 1230001010 n 40
삭제할 번호(여러개일 경우,로 구분) > 10


In [ ]:
# 업데이트
# 데이터를 조회 -> 업데이트할 번호 한개선택
# 순서대로 업데이트할 문장을 입력 -- author, title, year, isbn, amt 순서대로
# 해당 데이터로 업데이트를 진행
result = search_book(bookstore)
for data in result:
  print(data)

update_id = input('업데이트할 번호 > ')
for book in bookstore.books:
  if update_id == str(book.id):
    author, title, year, isbn, amt = input("Input book data(author, title, year, isbn, amt) >").strip().split()
    book.author = author
    book.title = title
    book.year = year
    book.isbn = isbn
    book.amt = amt

검색어 조회조건(검색어, 저자, 제목, 년도, isbn) >2020 년도
10 홍홍홍 파파파 2020 100100 n 100
업데이트할 번호 > 10
Input book data(author, title, year, isbn, amt) >홍길동 인공지능 2023 10203040 20


In [ ]:
# 단위테스트 :
# 서점객체생성
# 책 객체를 가가가 여러개 만들어서 데이터베이스(서점객체 내부의 리스트)에 저장한다

bookstore = BookStore()  # 서점객체
# 화이트홀 2024-09-01 카를로_로벨리 9791165349936 100
author, title, year, isbn, amt = input("Input book data(author, title, year, isbn, amt) >").strip().split()
book1 = Book(author, title, year, isbn, amt)
bookstore.books = book1

author, title, year, isbn, amt = input("Input book data(author, title, year, isbn, amt) >").strip().split()
book2 = Book(author, title, year, isbn, amt)
bookstore.books = book2

for book in bookstore.books:  # 데이터베이스의 모든 값을 출력
  print(book)

Input book data(author, title, year, isbn, amt) >화이트홀 2024-09-01 카를로_로벨리 9791165349936 100
Input book data(author, title, year, isbn, amt) >화이트홀 2024-09-01 카를로_로벨리 9791165349938 100
6 화이트홀 2024-09-01 카를로_로벨리 9791165349936 n 100
7 화이트홀 2024-09-01 카를로_로벨리 9791165349938 n 100


In [ ]:
class Temp:
  def __init__(self, data):
    self.data = data
  def __eq__(self,o):
    return self.data == o.data
  def __ne__(self,o):
    return self.data != o.data

t1 = Temp(1)
t2 = Temp(1)
t_list = [t1]
t2 in t_list

True

In [ ]:
class Book:
  serial_number = 0
  def __init__(self,author,title,year,isbn,amt=1):
    Book.serial_number += 1  # 고유 순번을 위해 객체생성시 1씩 증가하는 클래스변수
    self.author = author
    self.title = title
    self.year = year
    self.isbn = isbn
    self.delete_yn = 'n'
    self.amt = amt
    self.id = Book.serial_number  # PK

  def __eq__(self, __o: object) -> bool:  # 재 정의
    return self.isbn == __o.isbn
  def __ne__(self, __o: object) -> bool:  # 재 정의
    return self.isbn != __o.isbn

  def __str__(self):
    return f'{self.id} {self.author} {self.title} {self.year} {self.isbn} {self.delete_yn} {self.amt}'

class BookStore:
  def __init__(self) -> None:
    self.__books = []  # private  why? 리스트에 book 객체만 담기위해서 직접 접근을 금지

  @property  # getter
  def books(self):
    return self.__books

  @books.setter
  def books(self,book):
    if isinstance(book,Book) and book not in self.__books:  # 중복 체크
      self.__books.append(book)
    else:  # 사용자 정의 예외를 발생
      raise Exception('입력 오류')  # 차후 에 Exception을 상속받은 사용자 정의 예외 클래스가 필요함
  # Create
  def create_book(self):
    author,title,year,isbn,amt = input("input book data(author,title,year,isbn,amt) >").strip().split()
    book = Book(author,title,year,isbn,amt)
    self.books = book

  # Search
  def search_book(self):
    search, condition = input("검색어 조회조건(검색어, [저자, 제목, 년도 ,isbn]) > ").strip().split()
    if condition == '저자':
      return [ book for book in self.books if book.author == search and book.delete_yn.lower() == 'n']
    elif condition == '제목':
      return [ book for book in self.books if book.title == search and book.delete_yn.lower() == 'n']
    elif condition == '년도':
      return [ book for book in self.books if book.year == search and book.delete_yn.lower() == 'n']
    elif condition == 'isbn':
      return [ book for book in self.books if book.isbn == search and book.delete_yn.lower() == 'n']
    else:
      raise Exception('조회조건 오류')
  # Update
  def update_book(self):
    update_str =  int(input('업데이트할 번호 > '))
    author,title,year,isbn  = input("업데이트할 내용을 순서대로 작성(저자, 제목, 년도 ,isbn) > ").strip().split()
    for book in self.books:
      if book.id == update_str:
        book.author = author
        book.title = title
        book.year = year
        book.isbn = isbn
        break
  # Delete
  def delete_book(self):
    result = self.search_book()  # 삭제할 책을 찾는다
    for data in result:  # 찾은 내용을 출력
      print(data)

    delete_str =  input('삭제할 번호(여러개일 경우 ,로 구분) > ').strip().split(',')
    for id in map(int,delete_str):
      for book in self.books:
        if book.id == id:
          book.delete_yn = 'y'
          break
# 일반함수
def display_get_Menu():
  print('1.입력\t\t2.조회\n3.업데이트\t4.삭제\n5.종료')
  menu_num = int(input("input > "))
  if 1<=menu_num<=5:
    return menu_num
  else:
    raise Exception('메뉴번호 오류')

In [ ]:
store = BookStore()

In [ ]:
# 메일 실행부
try:
  menu_num = display_get_Menu() # 메뉴를 보여주고 사용자로부터 번호를 받는다
  if menu_num == 1:
    store.create_book()
  elif menu_num == 2:
    for book in store.search_book():
      print(book)
  elif menu_num == 3:
    for book in store.search_book():   # 검색한 목록을 보여주기
      print(book)
    store.update_book()
  elif menu_num == 4:
    store.delete_book()
  elif menu_num == 5:
    pass
except Exception as e:
  print(e)

1.입력		2.조회
3.업데이트	4.삭제
5.종료
input > 4
검색어 조회조건(검색어, [저자, 제목, 년도 ,isbn]) > 2024 년도
1 홍길동 인공지능 2024 112244 n 10
삭제할 번호(여러개일 경우 ,로 구분) > 1


In [ ]:
for i in store.books:
  print(i)

1 홍길동 인공지능 2024 112244 y 10


정리
 - 함수에 데이터 전달하고 받고
 - 클래스 안에서 데코레이션.. property

In [ ]:
# 함수 정의
 # 명령어들의 모음

In [ ]:
# 사각형의 넓이를 구하는 코드
# 공식...
# 가로 * 세로
def getRectangleArea(w,h=1,a=1): # defult parameter로 오버로드 불가 문제 대체
  # w = 20
  # h = 30

  return w * h * a

In [ ]:
getRectangleArea(30, a = 1, h = 2)

60

In [ ]:
# 함수 - 순서대로 1대 1 매칭

In [ ]:
def getSum(*args, count):
  return args

In [ ]:
getSum(1,10,20,30,40,50, count = 100)

(1, 10, 20, 30, 40, 50)

In [ ]:
# *args 가변매개변수, 튜플 형태로 전달받는다
# **args 가변매개변수, 튜플 형태로 전달받는다 key = value 형태로 전달받은 데이터를 'key':'value인 dict형태로 변환
def getSum(**args):
  return args

In [ ]:
getSum(a=10,b=20,c=30)

{'a': 10, 'b': 20, 'c': 30}